import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "IdealFurniture",
  description: "Generated by Salaar Asim",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased bg-background-light text-text-light">
        {children}
      </body>
    </html>
  );
}
