import type { Metadata } from "next";
import Script from "next/script";
import { Work_Sans } from "next/font/google";
import "./globals.css";

// ✅ Self-hosted Google Font (NO render blocking)
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "IdealFurniture",
  description: "Generated by Salaar Asim",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <head>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-NC4P95D1E0"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-NC4P95D1E0');
          `}
        </Script>

        {/* Preload hero image (LCP optimization) */}
        <link
          rel="preload"
          as="image"
          href="/images/img1.webp"
          fetchPriority="high"
        />

        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body
        className={`${workSans.className} antialiased bg-background-light text-light`}
      >
        {children}
      </body>
    </html>
  );
}
